name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  go_router: ^13.2.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  path: ^1.9.0
  tuple: ^2.0.0
  sqflite_common_ffi_web: ^0.4.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets: 
    - images/cherry.jpg
    - images/example.png
    - images/appIcon/icon_prod.png
    - images/appIcon/icon_uat.png